language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_install:
- npm config set //registry.npmjs.org/:_authToken=$npm_token
script:
  - cd react-example
  - npm install
  - npm run build
  - cd ../topup
  - npm install
  - cd ../leverage
  - npm install
  - npm run build

