language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - cd react-example
  - npm build
  - cd ../topup
  - npm build
  - cd ../leverage
  - npm build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
