language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
  - react-example/node_modules
  - topup/node_modules
  - leverage/node_modules
before_install:
- npm config set //registry.npmjs.org/:_authToken=$npm_token
script:
  - cd react-example
  - npm install
  - npm run build
  - cd ../topup
  - npm install
  - npm test
  - cd ../leverage
  - npm install
  - npm test
