language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
  - react-example/node_modules
  - topup/node_modules
  - leverage/node_modules
env:
  - NETWORK="decentralized-oasis-without-proxies"
before_install:
- npm config set //registry.npmjs.org/:_authToken=$npm_token
script:
  - cd react-example
  - yarn install
  - yarn build
  - cd ../topup
  - yarn install
  - yarn test
  - cd ../leverage
  - yarn install
  - yarn test
